pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    args '-u root'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
        stage('Unit Tests - Frontend') {
            agent {
                docker {
                    inage 'node:20-alpine'
                    args '-u root'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                      npm ci
                      npm test
                    '''
                }
            }
        }
    }
}
